version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Itbs@Dev123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  maintenance-api:
    build: .
    container_name: maintenance-api
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=maintenance_db;
      - SPRING_DATASOURCE_USERNAME=hazem
      - SPRING_DATASOURCE_PASSWORD=Itbs@Dev123

volumes:
  sqlserver_data:
